

<div class="login-form">
    <form action="" method="post">
        <h2 class="text-center"><img src="<?php echo $this->basepath('img/logo.png') ?>" class="img-responsive" alt=""></h2>       
        <br/>
        <div class="form-group">
            <input type="text" class="form-control" placeholder="Ingrese su email" id="username" name="username" required="required">
        </div>
        <div class="form-group">
            <input type="password" class="form-control" placeholder="Ingrese su número de documento" id="passwd" name="passwd" required="required">
        </div>
        <div class="form-group">
            <button type="submit" class="btn btn-primary btn-block">Iniciar sesión</button>
            <?php if($this->error){ ?>
                <p style='color: red; text-align:center;margin-top:15px'><?php echo $this->error ?></p>
            <?php } ?>
        </div>
<!--        <div class="clearfix">
            <label class="pull-left checkbox-inline"><input type="checkbox"> Remember me</label>
            <a href="#" class="pull-right">Forgot Password?</a>
        </div>        -->
    </form>
    <!--<p class="text-center"><a href="#">Create an Account</a></p>-->
</div>