    <div class="section__content section__content--p30">
                    <div class="container-fluid">                     
                     
                        <div class="row">
                            <div class="col-lg-12">
                                <h2>Bienvenido al 4to Foro de Energías Renovables</h2>
                                <br/>
                                <?php if(count($this->pago) > 0){ ?>
                                <p>Recuerde presentar el ticket al momento de entrar al evento para verificar su ingreso.</p>
                                <br/>
                                <a class="btn btn-primary" href="http://pdfgen.linkeventt.com/?code=<?php echo $this->pago[0]['code'] ?>&nrodoc=<?php echo $this->pago[0]['nrodoc'] ?>" target="_blank">Descargar entradas</a>
                                <?php } else { ?>                                
                                <h3>Una vez registrado su pago podrá acceder a las entradas del evento</h3>
                                <?php } ?>
                            </div>
     
                        </div>
<!--                        <div class="row">
                            <div class="col-md-12">
                                <div class="copyright">
                                    <p>Copyright © 2019 Linkeventt. All rights reserved. Template by <a href="https://colorlib.com">Colorlib</a>.</p>
                                </div>
                            </div>
                        </div>-->
                    </div>
                </div>

<?php $this->headScript()->appendFile($this->basepath('js/inscritos/inscritos_main.js')); ?>