<style>
    .error{
        color: red;
    }
</style>  
<div class="section__content section__content--p30">
                    <div class="container-fluid">                     
                     
                        <div class="row">
                            <div class="col-lg-12">
                                <h2 class="title-1 m-b-25">Nuevo pago</h2>
                                <br/><br/>
                                <form id="form-registrarpago">
                                    <div class="form-row">
                                        <div class="form-group col-md-6">
                                            <label for="medio">Medio de pago</label>
                                            <select id="medio" name="medio" class="form-control">                                            
                                              <option selected="" value="0">Seleccione una opción...</option>
                                              <option value="1">Pago en línea</option>
                                              <option value="2">Consignación bancaria</option>                 
                                            </select>
                                          </div> 
                                        <div class="form-group col-md-6">
                                          <label for="valor">Valor</label>
                                          <input type="text" class="form-control" id="valor" name="valor" placeholder="Valor de la consignación" value="">
                                        </div>   
                                        <div class="form-group col-md-6">
                                          <label for="fecha">Fecha</label>
                                          <input type="text" class="form-control datepicker-here"  data-language='es' data-date-format="yyyy-mm-dd" id="fecha" name="fecha" placeholder="Fecha de la consignación" value="">
                                        </div> 
                                     <div class="form-group col-md-6">
                                          <label for="cod_seguimiento">Código de seguimiento</label>
                                          <input type="text" class="form-control" id="cod_seguimiento" name="cod_seguimiento" placeholder="Código de seguimiento" value="">
                                        </div>   
                                        <div class="form-group col-md-12">
                                          <label for="comprobante">Comprobante de pago</label>
                                          <input type="file" class="comprobante" name="comprobante"/>                                        
                                        </div> 
                                        <input type="hidden" name="archivo_id" id="archivo_id" value="" />
                                      </div>
                                         
                                      </div>
                                        
                                      </div>
                                    
                                    <div class="usuarios_list">
                                        <p>Persona</p>
                                        <table class="table table-striped" id="grid">
                                            <thead>
                                                <th data-column-id='user_id' data-identifier='user_id' data-formatter="radio">&nbsp;</th>
                                                <th data-column-id='nombre' data-identifier='nombre'>Nombre</th>
                                                <th data-column-id='email' data-identifier='email'>Email</th>
                                                <th>&nbsp;</th>
                                            </thead>
                                            <tbody>
                                                <?php foreach($this->pagos as $p){ ?>
                                                <tr>
                                                    <td>
                                                        <?php echo $p['user_id'] ?>
                                                    </td>
                                                <td><?php echo strtoupper($p['nombres']) ?> <?php echo strtoupper($p['apellidos']) ?></td>                                         
                                                <td><?php echo strtolower($p['email']) ?></td>
                                                </tr>
                                                <?php } ?>
                                            </tbody>
                                        </table>
                                    </div>
                                    <div class="controls" style="margin-top: 30px; padding: 20px; text-align:center">
                                        <button type="submit" class="btn btn-primary">Registrar pago</button>
                                    </div>
                                </form>
                            </div>
     
                        </div>
<!--                        <div class="row">
                            <div class="col-md-12">
                                <div class="copyright">
                                    <p>Copyright © 2019 Linkeventt. All rights reserved. Template by <a href="https://colorlib.com">Colorlib</a>.</p>
                                </div>
                            </div>
                        </div>-->
                    </div>
                </div>

<?php 
$this->headScript()->appendFile($this->basepath('/js/vendor/jquery-validation-1.19.0/jquery.validate.min.js'));
$this->headScript()->appendFile($this->basepath('/js/vendor/jquery-validation-1.19.0/additional-methods.min.js'));
$this->headScript()->appendFile($this->basepath('/js/vendor/jquery-validation-1.19.0/localization/messages_es.min.js'));
$this->headLink()->appendStylesheet($this->basepath('/js/vendor/air-datepicker/css/datepicker.min.css')); 
$this->headScript()->appendFile($this->basepath('/js/vendor/air-datepicker/js/datepicker.min.js')); 
$this->headScript()->appendFile($this->basepath('/js/vendor/air-datepicker/js/i18n/datepicker.es.js')); 
$this->headLink()->appendStylesheet('https://unpkg.com/filepond/dist/filepond.css'); 
$this->headScript()->appendFile('https://unpkg.com/filepond/dist/filepond.min.js'); 
$this->headScript()->appendFile('https://unpkg.com/jquery-filepond/filepond.jquery.js'); 
$this->headScript()->appendFile($this->basepath('js/pagos/registrarpago.js')); 
?>