<style>
    .error{
        color: red;
    }
</style>  
<div class="section__content section__content--p30">
                    <div class="container-fluid">                     
                     
                        <div class="row">
                            <div class="col-lg-12">
                                <h2 class="title-1 m-b-25">Nuevo email masivo</h2>
                                <br/><br/>
                                <form id="form-emailmasivo">
                                    <div class="form-row">
                                        <div class="form-group col-md-6">
                                          <label for="etiqueta">Etiqueta</label>
                                          <input type="text" class="form-control" id="etiqueta" name="etiqueta" placeholder="Etiqueta del email masivo" value="">
                                        </div>   
                                        <div class="form-group col-md-6">
                                            <label for="tipo_envio">Tipo de envío</label>
                                            <select id="tipo_envio" name="tipo_envio" class="form-control">                                            
                                              <option selected="" value="0">Seleccione una opción...</option>
                                              <option value="1">Recordatorio de pago</option>
                                              <option value="2">Envío de usuarios</option>
                                              <option value="3">Envío de entradas</option>
                                            </select>
                                          </div> 
                                      </div>
                                    <div class="usuarios_list">
                                        <p>Usuarios a enviar</p>
                                        <table class="table table-striped" id="ulist">
                                            <thead>
                                                <th><input type="checkbox" name="checkall"></th>
                                                <th>Nombre</th>
                                                <th>Email</th>
                                                <th>&nbsp;</th>
                                            </thead>
                                            <tbody>
                                                <tr>
                                                    <td colspan="4">No hay resultados</td>
                                                </tr>
                                            </tbody>
                                        </table>
                                    </div>
                                    <div class="controls" style="margin-top: 30px; padding: 20px; text-align:center">
                                        <button type="submit" class="btn btn-primary">Enviar email</button>
                                    </div>
                                </form>
                            </div>
     
                        </div>
<!--                        <div class="row">
                            <div class="col-md-12">
                                <div class="copyright">
                                    <p>Copyright © 2019 Linkeventt. All rights reserved. Template by <a href="https://colorlib.com">Colorlib</a>.</p>
                                </div>
                            </div>
                        </div>-->
                    </div>
                </div>

<?php 
$this->headScript()->appendFile($this->basepath('/js/vendor/jquery-validation-1.19.0/jquery.validate.min.js'));
$this->headScript()->appendFile($this->basepath('/js/vendor/jquery-validation-1.19.0/additional-methods.min.js'));
$this->headScript()->appendFile($this->basepath('/js/vendor/jquery-validation-1.19.0/localization/messages_es.min.js'));
$this->headScript()->appendFile($this->basepath('js/comunicaciones/startemail_main.js')); 
?>