<style>
    .pagination li{
        padding-left: 5px;
        cursor: pointer;
    }
</style>
<div class="section__content section__content--p30">
                    <div class="container-fluid">                     
                     
                        <div class="row">
                            <div class="col-lg-12">                                 
                                <h2 class="title-1 m-b-25">Tickets cortesia del evento <a target="_blank" href="<?php echo $this->basepath('/dashboard/reportepagos') ?>" class="btn btn-primary">Descargar</a></h2>
                                <div class="table-responsive table--no-card m-b-40">
                                    <table class="table table-striped" id='grid'>
                                        <thead>
                                            <tr>
                                                <th data-column-id='id' data-identifier='id'>#</th>
                                                <th data-column-id='fecha' data-identifier='fecha'>Fecha</th>
                                                <th data-column-id='persona' data-identifier='persona'>Persona</th>
                                                <th data-column-id='nrodoc' data-identifier='nrodoc'>Nrodoc</th>
                                                <th data-column-id='email' data-identifier='email'>Email</th>
                                                <th data-column-id='medio' data-identifier='medio'>Medio de pago</th>
                                                <th data-column-id='url' data-identifier='url' data-formatter="file_download">Comprobante</th>                                           
                                                <th data-column-id='ticket' data-identifier='ticket' data-formatter="enviar_ticket">Ticket</th>                                           
                                            </tr>
                                        </thead>
                                        <tbody>
                                            <?php foreach($this->pagos as $key=>$p) { ?>
                                            <tr>
                                                <td><?php echo $key+1 ?></td>
                                                <td><?php echo $p['fecha'] ?></td>
                                                <td><?php echo strtoupper($p['nombres']) ?> <?php echo strtoupper($p['apellidos']) ?></td>                                         
                                                <td><?php echo $p['nrodoc'] ?></td>
                                                <td><?php echo strtolower($p['email']) ?></td>
                                                <td><?php echo $p['medio'] == 1 ? 'PayU' : 'Consignación' ?></td>
                                                <td><?php echo $p['url'] ?></td>                                              
                                                <td><?php echo $p['id'] ?></td>                                              
                                            </tr>
                                            <?php } ?>

                                        </tbody>
                                    </table>
                                </div>
                        
                            </div>
     
                        </div>
<!--                        <div class="row">
                            <div class="col-md-12">
                                <div class="copyright">
                                    <p>Copyright © 2019 Linkeventt. All rights reserved. Template by <a href="https://colorlib.com">Colorlib</a>.</p>
                                </div>
                            </div>
                        </div>-->
                    </div>
                </div>

<?php $this->headScript()->appendFile($this->basepath('js/pagos/pagos_main.js')); ?>