<section>
<div class="container">
      <div class="row">
        
        <div class="col-lg-12">
          <div class="p-2" style="text-align:center">            
            <h2 class="display-4">¡Crea tu evento!</h2>
            <p>Ingresa los datos de tu evento y enviaremos a tu correo el acceso a Linkeventt.</p>
          </div>
        </div>
        <div class="col-md-4 mx-auto">
            <div class="myform form ">
               <form action="" method="post" name="registroevento">
                      <div class="form-group">
                             <input type="text" name="evento"  class="form-control my-input" id="name" placeholder="Nombre del evento">
                             <?php echo $this->field == 'evento' ?  '<p class="error">'.$this->error.'</p>' : '' ?>
                      </div>
                      <div class="form-group">
                             <input type="text" name="organizador"  class="form-control my-input" id="email" placeholder="Nombre completo organizador">
                             <?php echo $this->field == 'organizador' ?  '<p class="error">'.$this->error.'</p>' : '' ?>
                      </div>
                      <div class="form-group">
                             <input type="text" name="email"  class="form-control my-input" id="name" placeholder="Email organizador">
                             <?php echo $this->field == 'email' ?  '<p class="error">'.$this->error.'</p>' : '' ?>
                      </div>
                      <div class="form-group">
                             <input type="text" name="telefono"  class="form-control my-input" id="email" placeholder="Teléfono">
                             <?php echo $this->field == 'telefono' ?  '<p class="error">'.$this->error.'</p>' : '' ?>
                      </div>
                      
                      <div class="text-center ">
                             <button type="submit" class=" btn btn-block send-button tx-tfm">¡Crea tu evento!</button>
                             <?php if(isset($this->error) && !isset($this->field)){ ?>
                                <p class="error"> <?php echo $this->error; ?> </p>
                             <?php } ?>
                      </div>

                      <p class="small mt-3">Al iniciar sesión, usted está indicando
                          que ha leído y está de acuerdo con los <a href="#" class="ps-hero__content__link">Términos de Uso</a> y nuestra <a href="#">Política de Privacidad</a>.
                      </p>
               </form>
            </div>
	 </div>
      </div>
</div>
  </section>
<?php echo $this->headLink()->appendStylesheet($this->basepath('css/formaddevent.css')); ?> 
