<style>
    .pagination li{
        padding-left: 5px;
        cursor: pointer;
    }
</style>
<div class="section__content section__content--p30">
                    <div class="container-fluid">                     
                     
                        <div class="row">
                            <div class="col-lg-12">         
                                <div style="text-align: center;width:100%;margin-top: -20px">
                                <h3 class="title-1 m-b-20" >Confirmar asistencia</h3>
                                <p>La asistencia del participante ha sido confirmada.</p> 
                                </div>
                                
                            </div>
     
                        </div>

                    </div>
                </div>

<?php $this->headScript()->appendFile($this->basepath('js/inscritos/inscritos_main.js')); ?>