<style>
    .pagination li{
        padding-left: 5px;
        cursor: pointer;
    }
</style>
<div class="section__content section__content--p30">
                    <div class="container-fluid">                     
                     
                        <div class="row">
                            <div class="col-lg-12">         
                                <div style="text-align: center;width:100%;margin-top: -20px">
                                <h3 class="title-1 m-b-20" >Registrar asistente</h3>
                                </div>
                                 <div style="width: 100%;text-align: center">
                                   <a href="<?php echo $this->basepath('/asistencia/confirmarasistencia/'.$this->persona['inscripcion_id']) ?>" class="btn btn-primary btn-lg">Confirmar asistencia</a>
                                </div>
                                <table class="table" style="width: 100%;overflow-x:scroll ">
                                    <tr>
                                        <th>Nombre completo</th>                                       
                                    </tr>
                                    <tr>
                                        <td><h3 style="padding:0;margin-top:-20px"><?php echo $this->persona['nombres'] ?> <?php echo $this->persona['apellidos'] ?></h3></td>                                       
                                    </tr>
                                    <tr>
                                        <th>No. de documento</th>                                       
                                    </tr>
                                    <tr>
                                        <td><h3 style="padding:0;margin-top:-20px"><?php echo $this->persona['nrodoc'] ?></h3></td>                                       
                                    </tr>
                                    <tr>
                                        <th>Email</th>                                       
                                    </tr>
                                    <tr>
                                        <td><b style="padding:0;margin-top:-20px"><?php echo $this->persona['email'] ?></b></td>                                       
                                    </tr>
                                    <tr>
                                        <th>Teléfono</th>                                       
                                    </tr>
                                    <tr>
                                        <td><h3 style="padding:0;margin-top:-20px"><?php echo $this->persona['telefono'] ?></h3></td>                                       
                                    </tr>
                                    <tr>
                                        <th>Empresa</th>                                       
                                    </tr>
                                    <tr>
                                        <td><h3 style="padding:0;margin-top:-20px"><?php echo $this->persona['empresa'] ?></h3></td>                                       
                                    </tr>
                                    <tr>
                                        <th>Cargo</th>                                       
                                    </tr>  
                                    <tr>
                                        <td><h3 style="padding:0;margin-top:-20px"><?php echo $this->persona['cargo'] ?></h3></td>                                       
                                    </tr>
                                </table>
                                <br/>
                                <div style="width: 100%;text-align: center">
                                    <a href="<?php echo $this->basepath('/asistencia/confirmarasistencia/'.$this->persona['inscripcion_id']) ?>" class="btn btn-primary btn-lg">Confirmar asistencia</a>
                                </div>
                                <br/><br/>
                            </div>
     
                        </div>

                    </div>
                </div>

<?php $this->headScript()->appendFile($this->basepath('js/inscritos/inscritos_main.js')); ?>