<div class="py-0">
     <div class="d-block p-2" style="text-align: center">
      <h3 class="">Verificar inscripción</h3>
      <hr/>
    </div>
    <div class="container-fluid">
      <div class="row">
        <div class="col-md-3">&nbsp;</div>
        <div class="col-md-6">
          
          <?php if($this->confirmar == 1){ ?>
              <div class="alert alert-success alert-dismissible fade show" role="alert">
                <strong>Muy bien!</strong> Se ha inscrito correctamente al evento seleccionado.
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
              </div>
            <p>Puede iniciar sesión en el sistema para continuar.</p>
            <div style="height: 500px;">
                <a href="<?php echo $this->basepath('/auth/login')?>" class="btn btn-primary">Iniciar sesión</a>
            </div>
          <?php } ?>
          <?php if($this->notvalid == 1){ ?>
              <div class="alert alert-danger alert-dismissible fade show" role="alert">
                <strong>Error!</strong> No pudimos encontrar tu inscripción, intenta nuevamente.
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
              </div>            
            <div style="height: 500px;">
                <a href="<?php echo $this->basepath('/')?>" class="btn btn-primary">Regresar</a>
            </div>
          <?php } ?>
          
          
        </div>
      </div>
    </div>
  </div>