<?php
$this->headScript()->appendFile($this->basepath('/js/vendor/jquery-validation-1.19.0/jquery.validate.min.js'));
$this->headScript()->appendFile($this->basepath('/js/vendor/jquery-validation-1.19.0/additional-methods.min.js'));
$this->headScript()->appendFile($this->basepath('/js/vendor/jquery-validation-1.19.0/localization/messages_es.min.js'));
$this->headScript()->appendFile($this->basepath('/js/inscripciones/main.js'));
$this->headScript()->appendFile('/js/inscripciones/main.js');
?>
<style>
    .error{
        color: red;
    }
</style>
<div class="py-0">
            
     
   <div class="container-fluid">
    <div class="row">
        <div class="col-md-12 p-0" style="background: url('<?php echo $this->basepath('/img/molinos.png') ?>') no-repeat; width: 100%; background-size:cover; text-align:center; padding: 30px; height: 210px;">
                  <div class="d-block p-2" style="text-align: center; color: #fff; padding-top: 50px !important">
                    <h1 class="mb-1" style="font-size: 48px;">Contacto</h1>
                    <h3 class="">4to Foro Internacional de Energías Renovables</h3>
                  </div>
      
            </div>
    </div>
</div>

                  <nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="<?php echo $this->basepath('/') ?>">Inicio</a></li>
    <li class="breadcrumb-item"><a href="<?php echo $this->basepath('/') ?>">4to Foro Internacional de Energías Renovables</a></li>
    <li class="breadcrumb-item active">Contacto</li>
  </ol>
</nav>
<div class="container-fluid">
    <div class="row">
        <div class="col-md-12">
          
          
        </div>
           <br/>
         
          <div class="col-sm-6">
              <?php if($this->success == 1){ ?>
              <div class="alert alert-success alert-dismissible fade show" role="alert">
                <strong>Muy bien!</strong> Se ha enviado su mensaje correctamente. 
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
              </div>
                
              
          <?php } ?>
          <?php if($this->fail == 1){ ?>
              <div class="alert alert-danger alert-dismissible fade show" role="alert">
                <strong>Error!</strong> No se pudo enviar el mensaje. Intente nuevamente.
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
              </div>
       <?php } ?>
              <form id="form-contacto" class="p-3" action="<?php echo $this->basepath('/eventos/enviarmensaje') ?>" method="post">
              <h2>Formulario de contacto</h2>
                  <input type="hidden" name="evento_id" id="evento_id" value="1" />
            <div class="form-row">
              <div class="form-group col-md-12">
                <input type="text" class="form-control" id="nombres" name="nombres" placeholder="Nombre completo" value="">
              </div>
              <div class="form-group col-md-12">
                <input type="text" class="form-control" id="email" name="email" placeholder="Email" value="">
              </div>
              <div class="form-group col-md-12">
                <input type="text" class="form-control" id="asunto" name="asunto" placeholder="Asunto" value="">
              </div>
              <div class="form-group col-md-12">
                  <textarea class="form-control" id="mensaje" name="mensaje" placeholder="Mensaje" style='height:200px'></textarea>
              </div>
            </div>
          
            <div class="form-row">              
              <div class="form-group col-md-12" style='text-align: center'>
                <button type="submit" id="enviar" class="btn btn-primary btn-lg">Enviar mensaje</button>
                &nbsp;&nbsp;&nbsp;
                <a href="<?php echo $this->basepath('/foroenergia')?>" class="btn btn-outline-primary btn-lg">< Volver al evento</a>
                <br/>
                <br/>
                <a href="https://wa.me/573053556521" class="btn btn-outline-secondary btn-lg btn-block">Contactar vía Whatsapp</a>
              
               
                <div class="followus" style='border-radius: 5px; border: 1px solid #4f70ce; padding: 20px; color: #4f70ce'>
                    <h3 style='font-size: 22px'>Nuestras redes sociales</h3>
                    <a href="https://www.facebook.com/foroenergia" style='color: #4f70ce'><i class="fa fa-facebook-f"></i></a>
                    <a href="https://twitter.com/foroenergiar" target='_blank' style='color: #4f70ce'><i class="fa fa-twitter"></i></a>
                    <a href="https://instagram.com/foroenergia" style='color: #4f70ce'><i class="fa fa-instagram"></i></a>
                    <br/>
                 
                </div>
              </div>
            </div>
          </form>
          
          
        </div>
          <div class="col-sm-6">
              <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3952.195133916834!2d-76.63669350113256!3d7.8746402942988185!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x8e500dcd76f97f6f%3A0xd779315a91c70fb2!2sCentro+Empresarial+Santa+Mar%C3%ADa.!5e0!3m2!1ses-419!2sco!4v1554093445534!5m2!1ses-419!2sco"  height="450" frameborder="0" style="border:0;width:100%" allowfullscreen></iframe>
              <h2>Sede del evento: <span style="font-weight:bold">Auditorio Centro Empresarial Santa María</span> de la ciudad de <span style="font-weight:bold">Apartadó-Antioquia</span>, Fecha <span style="font-weight:bold">30 y 31 de mayo</span>.</h2>
          </div>
           
      </div>
    </div>
  </div>