<style>
    .pb-100 {
	padding-bottom: 100px;
}
.pt-100 {
	padding-top: 100px;
}
a{
    text-decoration:none;
}
.section-title h4 {
  font-size: 14px;
  font-weight: 500;
  color: #777;
}
.section-title h2 {
	font-size: 32px;
	text-transform: capitalize;
	margin: 15px 0;
	display: inline-block;
	position: relative;
	font-weight: 700;
	padding-bottom: 15px;
	letter-spacing: 1px;
	text-transform: uppercase;
}
.section-title p {
	font-weight: 300;
	font-size: 14px;
}
.black-bg .section-title h2, .black-bg .section-title h4, .black-bg .section-title p {
  color:#fff
}
.section-title h2:before {
  position: absolute;
  content: "";
  width: 150px;
  height: 1px;
  background-color: #777;
  bottom: 0;
  left: 50%;
  margin-left: -75px;
}
.section-title h2:after {
  position: absolute;
  content: "";
  width: 80px;
  height: 3px;
  background-color: #e16038;
  border: darkblue;
  bottom: -1px;
  left: 50%;
  margin-left: -40px;
}
.section-title {
  margin-bottom: 70px;
}
.single-price {
	text-align: center;
	padding: 30px;
	box-shadow: 0px 0px 2px rgba(0, 0, 0, 0.2);
}
.price-title h4 {
  font-size: 24px;
  text-transform: uppercase;
  font-weight: 600;
}
.price-tag {
  margin: 30px 0;
}
.price-tag {
	margin: 30px 0;
	color: #000;
	padding: 10px 0;
}
.center.price-tag {
	background-color: tomato;
	color:#fff
}
.price-tag h2 {
	font-size: 45px;
	font-weight: 600;
	font-family: poppins;
}
.price-tag h2 span {
  font-weight: 300;
  font-size: 16px;
  font-style: italic;
}
.price-item ul {
  margin: 0;
  padding: 0;
  list-style: none;
}
.price-item ul li {
  font-size: 20px;
  padding: 5px 0;
  border-bottom: 1px dashed #eee;
  margin: 5px 0;
}
.price-item ul li:last-child {
  border-bottom: 0;
}
.single-price a {
  margin-top: 15px;
}
a.box-btn {
	background-color: tomato;
	padding: 5px 20px;
	display: inline-block;
	color: #fff;
	text-transform: capitalize;
	border-radius: 3px;
	font-size: 15px;
	transition: .3s;
}
a.box-btn:hover, a.border-btn:hover {
	background-color: #d35400;
}
</style>
<div class="container-fluid">
    <div class="row">
        <div class="col-md-12 p-0" style="background: url('<?php echo $this->basepath('/img/molinos.png') ?>') no-repeat; width: 100%; background-size:cover; text-align:center; padding: 30px; height: 210px;">
                  <div class="d-block p-2" style="text-align: center; color: #fff; padding-top: 50px !important">
                    <h1 class="mb-1" style="font-size: 48px;">Patrocinio</h1>
                    <h3 class="">4to Foro Internacional de Energías Renovables</h3>
                  </div>
      
            </div>
    </div>
</div>

                  <nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="<?php echo $this->basepath('/') ?>">Inicio</a></li>
    <li class="breadcrumb-item"><a href="<?php echo $this->basepath('/') ?>">4to Foro Internacional de Energías Renovables</a></li>
    <li class="breadcrumb-item"><a href="<?php echo $this->basepath('/foroenergia/patrocinio') ?>">Patrocinio</a></li>
    <li class="breadcrumb-item active">Diamante</li>
  </ol>
</nav>
<div class="container-fluid">
    <div class="row">
        
        <div class="col-md-3">&nbsp;</div>
        <div class="col-md-6" style="font-size: 20px">
            <h1 style="text-align: center;padding: 30px">PATROCINADOR ALIADO DIAMANTE</h1>
            <div style="text-align: center; width: 100%">
            <img src="<?php echo $this->basepath('/img/diamante.png') ?>" style="width: 200px;padding: 15px;">
            </div>
            <p><i class="fa fa-check"></i> Derecho a ser nombrado con mensaje especial, como aliado principal en la apertura del evento </p>
            <p><i class="fa fa-check"></i> Derecho a colocar su logo en la valla publicitaria de la Sala VIP como nuestro aliado</p>
            <p><i class="fa fa-check"></i> Derecho a pasar video publicitario de la empresa de máximo 2 minuto durante 3 oportunidades, en el salón principal de conferencia y en la fiesta de cierre* </p>
            <p><i class="fa fa-check"></i> Publicación del logo de la empresa patrocinadora en la categoría Oro en los siguientes espacios:</p>
            <div style="margin-left:20px">
            <p> •	Home de la página web del evento con cobertura nacional e internacional</p>
            <p> •	Volantes digitales del evento</p>
            <p> •	Brochure académico del evento</p>
            <p> •	Newsletter promocionales</p>
            <p> •	Comunicaciones de promoción del evento</p>
            <p> •	Backing ubicado en el punto de registro</p>
            <p> •	Pendón digital Categoría oficial</p>
            </div>
            <p><i class="fa fa-check"></i> Derecho a entregar volante publicitario en el bolso de los participantes*.</p>
            <p><i class="fa fa-check"></i> Derecho a aparecer como patrocinador oficial junto con el organizador, en la valla sobre el escenario del evento en el auditorio principal.</p>
            <p><i class="fa fa-check"></i> Derecho a instalar una valla en la muestra comercial con la imagen de la compañía patrocinadora y algún mensaje clave que quieran elaborar (sujeto a dimensiones) *.</p>
            <p><i class="fa fa-check"></i> Derecho a incluir el logo de la empresa en la cinta de la escarapela (una sola tinta).</p>
            <p><i class="fa fa-check"></i> Derecho a instalar 2 pendones rollup en el auditorio principal*.</p>
            <p style="font-weight: bold; text-align: center">*Estos ítems deben ser suministrados directamente por la empresa patrocinadora</p>

            <h2 style="text-align: center;padding:30px">Inversión: $50.000.000 + IVA</h2>
            
        </div>
    </div>
</div>
