<style>
    .pb-100 {
	padding-bottom: 100px;
}
.pt-100 {
	padding-top: 100px;
}
a{
    text-decoration:none;
}
.section-title h4 {
  font-size: 14px;
  font-weight: 500;
  color: #777;
}
.section-title h2 {
	font-size: 32px;
	text-transform: capitalize;
	margin: 15px 0;
	display: inline-block;
	position: relative;
	font-weight: 700;
	padding-bottom: 15px;
	letter-spacing: 1px;
	text-transform: uppercase;
}
.section-title p {
	font-weight: 300;
	font-size: 14px;
}
.black-bg .section-title h2, .black-bg .section-title h4, .black-bg .section-title p {
  color:#fff
}
.section-title h2:before {
  position: absolute;
  content: "";
  width: 150px;
  height: 1px;
  background-color: #777;
  bottom: 0;
  left: 50%;
  margin-left: -75px;
}
.section-title h2:after {
  position: absolute;
  content: "";
  width: 80px;
  height: 3px;
  background-color: #e16038;
  border: darkblue;
  bottom: -1px;
  left: 50%;
  margin-left: -40px;
}
.section-title {
  margin-bottom: 70px;
}
.single-price {
	text-align: center;
	padding: 30px;
	box-shadow: 0px 0px 2px rgba(0, 0, 0, 0.2);
}
.price-title h4 {
  font-size: 24px;
  text-transform: uppercase;
  font-weight: 600;
}
.price-tag {
  margin: 30px 0;
}
.price-tag {
	margin: 30px 0;
	color: #000;
	padding: 10px 0;
}
.center.price-tag {
	background-color: tomato;
	color:#fff
}
.price-tag h2 {
	font-size: 45px;
	font-weight: 600;
	font-family: poppins;
}
.price-tag h2 span {
  font-weight: 300;
  font-size: 16px;
  font-style: italic;
}
.price-item ul {
  margin: 0;
  padding: 0;
  list-style: none;
}
.price-item ul li {
  font-size: 20px;
  padding: 5px 0;
  border-bottom: 1px dashed #eee;
  margin: 5px 0;
}
.price-item ul li:last-child {
  border-bottom: 0;
}
.single-price a {
  margin-top: 15px;
}
a.box-btn {
	background-color: tomato;
	padding: 5px 20px;
	display: inline-block;
	color: #fff;
	text-transform: capitalize;
	border-radius: 3px;
	font-size: 15px;
	transition: .3s;
}
a.box-btn:hover, a.border-btn:hover {
	background-color: #d35400;
}
</style>
<div class="container-fluid">
    <div class="row">
        <div class="col-md-12 p-0" style="background: url('<?php echo $this->basepath('/img/molinos.png') ?>') no-repeat; width: 100%; background-size:cover; text-align:center; padding: 30px; height: 210px;">
                  <div class="d-block p-2" style="text-align: center; color: #fff; padding-top: 50px !important">
                    <h1 class="mb-1" style="font-size: 48px;">Patrocinio</h1>
                    <h3 class="">4to Foro Internacional de Energías Renovables</h3>
                  </div>
      
            </div>
    </div>
</div>

                  <nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="<?php echo $this->basepath('/') ?>">Inicio</a></li>
    <li class="breadcrumb-item"><a href="<?php echo $this->basepath('/') ?>">4to Foro Internacional de Energías Renovables</a></li>
    <li class="breadcrumb-item"><a href="<?php echo $this->basepath('/foroenergia/patrocinio') ?>">Patrocinio</a></li>
    <li class="breadcrumb-item active">Otras formas de patrocinio</li>
  </ol>
</nav>
<div class="container-fluid">
    <div class="row">
        <div class="col-md-3">&nbsp;</div>
        <div class="col-md-6" style="font-size: 20px">
            <h1 style="text-align: center;padding: 30px">OTRAS FORMAS DE PATROCINIO</h1>
            <div style="text-align: center; width: 100%">
            <img src="<?php echo $this->basepath('/img/verde.png') ?>" style="width: 200px;padding: 15px;">
            </div>
            <h2>Escarapelas</h2>
            <img src="<?php echo $this->basepath('/img/escarapelas.png') ?>" style="width: 100%;padding: 15px;">
            <p><i class="fa fa-check"></i> Comercial con el logotipo de la empresa en todas las escarapelas de identificación de los participantes al evento (no incluye producción)</p>
            <p><i class="fa fa-check"></i> Pauta comercial con el logotipo de la empresa en todas las cintillas de las escarapelas de identificación de los participantes al evento (no incluye producción)</p>
            <p><i class="fa fa-check"></i> Derecho a instalar dos pendones de 2*1 m roll up con el logotipo de la empresa. Uno de ellos en la muestra comercial y otro en el camino de señalización hacia el salón de conferencias (Los pendones deben ser suministrados por la entidad patrocinadora)</p>
            <p><i class="fa fa-check"></i> Derecho a aparecer como patrocinador en la brochure digital del evento</p>
            <p><i class="fa fa-check"></i> Derecho a aparecer como patrocinador en la página web del evento</p>
            <p><i class="fa fa-check"></i> Derecho a aparecer como patrocinador en los pendones oficiales del evento en el salón de conferencias</p>
            <p><i class="fa fa-check"></i> Derecho a aparecer en el pendón digital en el salón de conferencias</p>
            
            <h2 style="text-align: center;padding:30px">Inversión: $8.000.000 + IVA</h2>
            
            <h2>Cuadernos y lapiceros ecológicos</h2>
            <img src="<?php echo $this->basepath('/img/libretas.png') ?>" style="width: 100%;padding: 15px;">
            <p><i class="fa fa-check"></i> Derecho a entregar cuadernos y esferos a todos los participantes del evento (El material corporativo debe ser suministrado por la entidad patrocinadora)</p>
            <p><i class="fa fa-check"></i> Derecho a instalar dos pendones de 2*1 m roll up con el logotipo de la empresa. Uno de ellos en la muestra comercial y otro en el camino de señalización hacia el salón de conferencias (Los pendones deben ser suministrados por la entidad patrocinadora)</p>
            <p><i class="fa fa-check"></i> Derecho a aparecer como patrocinador en la brochure digital del evento</p>
            <p><i class="fa fa-check"></i> Derecho a aparecer como patrocinador en la página web del evento</p>
            <p><i class="fa fa-check"></i> Derecho a aparecer como patrocinador en los pendones oficiales del evento en el salón de conferencias</p>
            <p><i class="fa fa-check"></i> Derecho a aparecer en el pendón digital en el salón de conferencias</p>
            
            <h2 style="text-align: center;padding:30px">Inversión: $5.000.000 + IVA</h2>
            
            <h2>Espaldares de sillas</h2>
            <img src="<?php echo $this->basepath('/img/espaldares.png') ?>" style="width: 100%;padding: 15px;">
            <p><i class="fa fa-check"></i> Publicación del logotipo del patrocinador en los espaldares de la silla 
                de la sala de conferencias (Los espaldares de las sillas deben ser suministrados por la entidad patrocinadora, 1000 unidades)
                </p>
            <p><i class="fa fa-check"></i> Derecho a instalar dos pendones de 2*1 m roll up con el logotipo de la empresa. Uno de ellos en la muestra comercial y otro en el camino de señalización hacia el salón de conferencias (Los pendones deben ser suministrados por la entidad patrocinadora)</p>
            <p><i class="fa fa-check"></i> Derecho a aparecer como patrocinador en la brochure digital del evento</p>
            <p><i class="fa fa-check"></i> Derecho a aparecer como patrocinador en la página web del evento</p>
            <p><i class="fa fa-check"></i> Derecho a aparecer como patrocinador en los pendones oficiales del evento en el salón de conferencias</p>
            <p><i class="fa fa-check"></i> Derecho a aparecer en el pendón digital en el salón de conferencias</p>
            
            <h2 style="text-align: center;padding:30px">Inversión: $7.000.000 + IVA</h2>
            
            <h2>Coffee break + Coffee break VIP</h2>
            <img src="<?php echo $this->basepath('/img/coffeebreak.png') ?>" style="width: 100%;padding: 15px;">
            <p><i class="fa fa-check"></i> Ubicación de piezas publicitarias durante los 3 Coffee Breaks 
                patrocinados: banderines, servilleteros y/o servilletas. (No incluye producción)              
                </p>
            <p><i class="fa fa-check"></i> Derecho a instalar dos pendones de 2*1 m roll up con el logotipo de la
                empresa en los sitios donde se entreguen los Coffee Breaks patrocinados. (Los pendones deben ser suministrados por la entidad patrocinadora)</p>
            <p><i class="fa fa-check"></i> Derecho a instalar un pendon de 2*1 m roll up con el logotipo de la 
                empresa en el camino de señalización hacia el salón de conferencias (El pendón deben ser suministrados por la entidad patrocinadora)</p>
            <p><i class="fa fa-check"></i> Derecho a aparecer como patrocinador en la brochure digital del evento</p>
            <p><i class="fa fa-check"></i> Derecho a aparecer como patrocinador en la página web del evento</p>
            <p><i class="fa fa-check"></i> Derecho a aparecer como patrocinador en los pendones oficiales del evento en el salón de conferencias y sala VIP</p>
            <p><i class="fa fa-check"></i> Derecho a aparecer en el pendón digital en el salón de conferencias</p>
            
            <h2 style="text-align: center;padding:30px">Inversión: $8.000.000 + IVA</h2>
            
            <h2>Valla escenario</h2>
            <img src="<?php echo $this->basepath('/img/vallaescenario.png') ?>" style="width: 100%;padding: 15px;">
            <p><i class="fa fa-check"></i> Derecho a publicar el logotipo de la empresa en la valla del escenario en el
                salón de conferencias. (Los organizadores del evento se encargarán de la producción)
                </p> 
            <p><i class="fa fa-check"></i> Derecho a instalar un pendon de 2*1 m roll up con el logotipo de la 
                empresa en el camino de señalización hacia el salón de conferencias (El pendón deben ser suministrados por la entidad patrocinadora)</p>
            <p><i class="fa fa-check"></i> Derecho a aparecer como patrocinador en la brochure digital del evento</p>
            <p><i class="fa fa-check"></i> Derecho a aparecer como patrocinador en la página web del evento</p>
            <p><i class="fa fa-check"></i> Derecho a aparecer como patrocinador en los pendones oficiales del evento en el salón de conferencias y sala VIP</p>
            <p><i class="fa fa-check"></i> Derecho a aparecer en el pendón digital en el salón de conferencias</p>
            
            <h2 style="text-align: center;padding:30px">Inversión: $6.000.000 + IVA</h2>
            
            <h2>Bolso ecológico + insertos</h2>
            <img src="<?php echo $this->basepath('/img/bolsas.png') ?>" style="width: 100%;padding: 15px;">
            <p><i class="fa fa-check"></i> Derecho a incluir un inserto en las mochilas de los participantes. (El material corporativo debe ser suministrado por la entidad patrocinadora, medida considerada 19 cms x 25 cms )</p> 
            <p><i class="fa fa-check"></i> Derecho a aparecer como patrocinador en el brochure digital del evento</p>
            <p><i class="fa fa-check"></i> Derecho a aparecer como patrocinador en la página web del evento</p>
            <p><i class="fa fa-check"></i> Derecho a aparecer como patrocinador en los pendones oficiales del evento en el salón de conferencias y sala VIP</p>
            <p><i class="fa fa-check"></i> Derecho a aparecer en el pendón digital en el salón de conferencias</p>
            
            <h2 style="text-align: center;padding:30px">Inversión: $6.500.000 + IVA</h2>
            
            <h2>Almuerzo invitados VIP</h2>
            <p><i class="fa fa-check"></i> Ubicación de piezas publicitarias durante almuerzo patrocinado: banderines, servilleteros y/o servilletas. (No incluye producción)</p> 
            <p><i class="fa fa-check"></i> Derecho a incluir el logotipo de la empresa en el menú del almuerzo que será distribuido a todos los participantes del evento (los menús serán producidos por los organizadores del evento)</p>
            <p><i class="fa fa-check"></i> Derecho a una mesa principal de 10 personas reservada para la entidad patrocinadora</p>
            <p><i class="fa fa-check"></i> Derecho a instalar dos pendones de 2*1 m Roll Up con el logotipo de la empresa en el lugar del almuerzo. (Los pendones deben ser suministrado por la entidad patrocinadora)</p>
            <p><i class="fa fa-check"></i> Derecho a entregar material publicitario durante el almuerzo patrocinado (El material publicitario debe ser suministrado por la entidad patrocinadora)</p>
                        <p><i class="fa fa-check"></i> Derecho a aparecer como patrocinador en el brochure digital del evento</p>
            <p><i class="fa fa-check"></i> Derecho a aparecer como patrocinador en la página web del evento</p>
            <p><i class="fa fa-check"></i> Derecho a aparecer como patrocinador en los pendones oficiales del evento en el salón de conferencias y sala VIP</p>
            <p><i class="fa fa-check"></i> Derecho a aparecer en el pendón digital en el salón de conferencias</p>
            <h2 style="text-align: center;padding:30px">Inversión: $7.000.000 + IVA</h2>
            
            <h2>Atril</h2>
            <img src="<?php echo $this->basepath('/img/atril.png') ?>" style="width: 100%;padding: 15px;">
            <p><i class="fa fa-check"></i> Derecho a publicar el logotipo de la empresa en el atril del salón de conferencias. (Los organizadores del evento se encargaran de la producción).</p> 
            <p><i class="fa fa-check"></i> Derecho a instalar 1 pendón de 2*1 m roll up con el logotipo de la empresa en el camino de señalización hacia el salón de conferencias (El pendón debe ser suministrados por la entidad patrocinadora)</p>
            <p><i class="fa fa-check"></i> Derecho a aparecer como patrocinador en la página web del evento</p>
            <p><i class="fa fa-check"></i> Derecho a aparecer como patrocinador en los pendones oficiales del evento en el salón de conferencias y sala VIP</p>
            <p><i class="fa fa-check"></i> Derecho a aparecer en el pendón digital en el salón de conferencias</p>
            <h2 style="text-align: center;padding:30px">Inversión: $4.500.000 + IVA</h2>
            
            <h2>Fiesta temática de cierre</h2>
            <img src="<?php echo $this->basepath('/img/fiestatematica.png') ?>" style="width: 100%;padding: 15px;">
            <p><i class="fa fa-check"></i> Ubicación de piezas publicitarias en el sitio de la Fiesta Temática</p> 
            <p><i class="fa fa-check"></i> Derecho a instalar dos pendones de 2*1 m Roll Up con el logotipo de la empresa en el lugar del coctel de bienvenida. (Los pendones deben ser suministrado por la entidad patrocinadora)</p> 
            <p><i class="fa fa-check"></i> Derecho a entregar material publicitario durante el coctel de bienvenida patrocinado (El material publicitario debe ser suministrado por la entidad patrocinadora)</p> 
            <p><i class="fa fa-check"></i> Derecho a instalar 1 pendon de 2*1 m roll up con el logotipo de la empresa en el camino de señalización hacia el salón de conferencias (El pendón debe ser suministrados por la entidad patrocinadora)</p>
            <p><i class="fa fa-check"></i> Derecho a aparecer como patrocinador en la página web del evento</p>
            <p><i class="fa fa-check"></i> Derecho a aparecer como patrocinador en los pendones oficiales del evento en el salón de conferencias y sala VIP</p>
            <p><i class="fa fa-check"></i> Derecho a aparecer en el pendón digital en el salón de conferencias</p>
            <h2 style="text-align: center;padding:30px">Inversión: $12.000.000 + IVA</h2>
            
        </div>
    </div>
</div>
