<style>
    .pb-100 {
	padding-bottom: 100px;
}
.pt-100 {
	padding-top: 100px;
}
a{
    text-decoration:none;
}
.section-title h4 {
  font-size: 14px;
  font-weight: 500;
  color: #777;
}
.section-title h2 {
	font-size: 32px;
	text-transform: capitalize;
	margin: 15px 0;
	display: inline-block;
	position: relative;
	font-weight: 700;
	padding-bottom: 15px;
	letter-spacing: 1px;
	text-transform: uppercase;
}
.section-title p {
	font-weight: 300;
	font-size: 14px;
}
.black-bg .section-title h2, .black-bg .section-title h4, .black-bg .section-title p {
  color:#fff
}
.section-title h2:before {
  position: absolute;
  content: "";
  width: 150px;
  height: 1px;
  background-color: #777;
  bottom: 0;
  left: 50%;
  margin-left: -75px;
}
.section-title h2:after {
  position: absolute;
  content: "";
  width: 80px;
  height: 3px;
  background-color: #e16038;
  border: darkblue;
  bottom: -1px;
  left: 50%;
  margin-left: -40px;
}
.section-title {
  margin-bottom: 70px;
}
.single-price {
	text-align: center;
	padding: 30px;
	box-shadow: 0px 0px 2px rgba(0, 0, 0, 0.2);
}
.price-title h4 {
  font-size: 24px;
  text-transform: uppercase;
  font-weight: 600;
}
.price-tag {
  margin: 30px 0;
}
.price-tag {
	margin: 30px 0;
	color: #000;
	padding: 10px 0;
}
.center.price-tag {
	background-color: tomato;
	color:#fff
}
.price-tag h2 {
	font-size: 45px;
	font-weight: 600;
	font-family: poppins;
}
.price-tag h2 span {
  font-weight: 300;
  font-size: 16px;
  font-style: italic;
}
.price-item ul {
  margin: 0;
  padding: 0;
  list-style: none;
}
.price-item ul li {
  font-size: 20px;
  padding: 5px 0;
  border-bottom: 1px dashed #eee;
  margin: 5px 0;
}
.price-item ul li:last-child {
  border-bottom: 0;
}
.single-price a {
  margin-top: 15px;
}
a.box-btn {
	background-color: tomato;
	padding: 5px 20px;
	display: inline-block;
	color: #fff;
	text-transform: capitalize;
	border-radius: 3px;
	font-size: 15px;
	transition: .3s;
}
a.box-btn:hover, a.border-btn:hover {
	background-color: #d35400;
}
</style>
<div class="container-fluid">
    <div class="row">
        <div class="col-md-12 p-0" style="background: url('<?php echo $this->basepath('/img/molinos.png') ?>') no-repeat; width: 100%; background-size:cover; text-align:center; padding: 30px; height: 210px;">
                  <div class="d-block p-2" style="text-align: center; color: #fff; padding-top: 50px !important">
                    <h1 class="mb-1" style="font-size: 48px;">Patrocinio</h1>
                    <h3 class="">4to Foro Internacional de Energías Renovables</h3>
                  </div>
            </div>
        
    </div>
</div>
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="<?php echo $this->basepath('/') ?>">Inicio</a></li>
    <li class="breadcrumb-item"><a href="<?php echo $this->basepath('/') ?>">4to Foro Internacional de Energías Renovables</a></li>
    <li class="breadcrumb-item active">Patrocinio</li>
  </ol>
</nav>
<section class="pricing-area pt-100 pb-100" id="pricing">
		<div class="container">			
			<div class="row">
               <div class="col-xl-3">
				<div class="single-price">
				  <div class="price-title">
					<h4>patrocinador aliado diamante</h4>
				  </div>
				  <div class="price-tag">
                                      <img src="<?php echo $this->basepath('/img/diamante.png') ?>" style="width: 200px">
					<h2><span>Incluye:</span></h2>
				  </div>
				  <div class="price-item">
					<ul>
                                            <li><i class="fa fa-check"></i> Derecho a ser nombrado con mensaje especial, como aliado principal en la apertura del evento </li>
				            <li><i class="fa fa-check"></i> Derecho a colocar su logo en la valla publicitaria de la Sala VIP como nuestro aliado y...</li>
					</ul>
				  </div>
				  <a href="<?php echo $this->basepath('/foroenergia/patrocinio/diamante') ?>" class="box-btn">ver más</a>
			   </div>
			   </div>
               <div class="col-xl-3">
				<div class="single-price">
				  <div class="price-title">
					<h4>patrocinador oficial oro</h4>
				  </div>
				  <div class="price-tag">
                                      <img src="<?php echo $this->basepath('/img/oro.png') ?>" style="width: 200px">
					<h2><span>Incluye:</span></h2>
				  </div>
				  <div class="price-item">
					<ul>
                                            <li><i class="fa fa-check"></i> Derechos exclusivos como patrocinador Oficial del evento en las imágenes dentro del auditorio y fuera.</li>
				            <li><i class="fa fa-check"></i> Derecho a colocar 1 pendón en la Sala VIP, 1 en la sala de Charlas técnicas y...</li>
					</ul>
				  </div>
				  <a href="<?php echo $this->basepath('/foroenergia/patrocinio/oro') ?>" class="box-btn">ver más</a>
			   </div>
			   </div>
               <div class="col-xl-3">
				<div class="single-price">
				  <div class="price-title">
                                      <h4>categoría<br/> plata</h4>
				  </div>
				  <div class="price-tag">
					<img src="<?php echo $this->basepath('/img/plata.png') ?>" style="width: 200px">
					<h2><span>Incluye:</span></h2>
				  </div>
				  <div class="price-item">
					<ul>
                                            <li><i class="fa fa-check"></i> Derecho a colocar 1 pendón en la sala de Charlas técnicas y 1 en el lugar de la fiesta de cierre.</li>
				            <li><i class="fa fa-check"></i> Derecho a espacio de 3 m2 en la muestra comercial...</li>
					</ul>
				  </div>
				  <a href="<?php echo $this->basepath('/foroenergia/patrocinio/plata') ?>" class="box-btn">ver más</a>
			   </div>
			   </div>
               <div class="col-xl-3">
				<div class="single-price">
				  <div class="price-title">
					<h4>otras formas de patrocinar</h4>
				  </div>
				  <div class="price-tag">
					<img src="<?php echo $this->basepath('/img/verde.png') ?>" style="width: 200px">
					<h2><span>Incluye:</span></h2>
				  </div>
				  <div class="price-item">
					<ul>
                                            <li><i class="fa fa-check"></i> Escarapelas</li>
                                            <li><i class="fa fa-check"></i> Cuadernos y lapiceros</li>
                                            <li><i class="fa fa-check"></i> Valla escenario</li>
                                            <li><i class="fa fa-check"></i> Espaldares de sillas</li>
					</ul>
				  </div>
				  <a href="<?php echo $this->basepath('/foroenergia/patrocinio/otros') ?>" class="box-btn">ver más</a>
			   </div>
			   </div>
            </div>
		</div>
	  </section>