<?php
session_start();
?>
<!DOCTYPE html>
<html lang="es">

<head>
    <!-- Required meta tags-->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="au theme template">
    <meta name="author" content="Genmotion Makers">
    <meta name="keywords" content="linkeventt">

    <!-- Title Page-->
    <title>Linkeventt Dashboard</title>

    <!-- Fontfaces CSS-->
    <link href="<?php echo $this->basepath('assets/dashboard2/css/font-face.css') ?>" rel="stylesheet" media="all">
    <link href="<?php echo $this->basepath('assets/dashboard2/vendor/font-awesome-4.7/css/font-awesome.min.css') ?>" rel="stylesheet" media="all">
    <link href="<?php echo $this->basepath('assets/dashboard2/vendor/font-awesome-5/css/fontawesome-all.min.css') ?>" rel="stylesheet" media="all">
    <link href="<?php echo $this->basepath('assets/dashboard2/vendor/mdi-font/css/material-design-iconic-font.min.css') ?>" rel="stylesheet" media="all">

    <!-- Bootstrap CSS-->
    <link href="<?php echo $this->basepath('assets/dashboard2/vendor/bootstrap-4.1/bootstrap.min.css') ?>" rel="stylesheet" media="all">

    <!-- Vendor CSS-->
    <link href="<?php echo $this->basepath('assets/dashboard2/vendor/animsition/animsition.min.css') ?>" rel="stylesheet" media="all">
    <link href="<?php echo $this->basepath('assets/dashboard2/vendor/bootstrap-progressbar/bootstrap-progressbar-3.3.4.min.css') ?>" rel="stylesheet" media="all">
    <link href="<?php echo $this->basepath('assets/dashboard2/vendor/wow/animate.css') ?>" rel="stylesheet" media="all">
    <link href="<?php echo $this->basepath('assets/dashboard2/vendor/css-hamburgers/hamburgers.min.css') ?>" rel="stylesheet" media="all">
    <link href="<?php echo $this->basepath('assets/dashboard2/vendor/slick/slick.css') ?>" rel="stylesheet" media="all">
    <link href="<?php echo $this->basepath('assets/dashboard2/vendor/select2/select2.min.css') ?>" rel="stylesheet" media="all">
    <link href="<?php echo $this->basepath('assets/dashboard2/vendor/perfect-scrollbar/perfect-scrollbar.css') ?>" rel="stylesheet" media="all">
    <link href="<?php echo $this->basepath('js/vendor/bootgrid/jquery.bootgrid.min.css') ?>" rel="stylesheet" media="all">

    <!-- Main CSS-->
    <link href="<?php echo $this->basepath('assets/dashboard2/css/theme.css') ?>" rel="stylesheet" media="all">
    
    
    <?php echo $this->headLink(); ?>
</head>

<body class="animsition">
    <div class="page-wrapper">
        <!-- HEADER MOBILE-->
        <header class="header-mobile d-block d-lg-none">
            <div class="header-mobile__bar">
                <div class="container-fluid">
                    <div class="header-mobile-inner">
                        <a class="logo" href="<?php echo $this->basepath('/dashboard') ?>"  style="width:150px">
                            <img src="<?php echo $this->basepath('img/logo.png') ?>" alt="Linkeventt" />
                        </a>
                      
                    </div>
                </div>
            </div>
            
        </header>
        <!-- END HEADER MOBILE-->

        <!-- MENU SIDEBAR-->
        <aside class="menu-sidebar d-none d-lg-block">
            <div class="logo">
                <a href="#">
                    <img src="<?php echo $this->basepath('img/logo.png') ?>" alt="Linkeventt" style='width: 179px;height:52px' />
                </a>
            </div>
            
        </aside>
        <!-- END MENU SIDEBAR-->

        <!-- PAGE CONTAINER-->
        <div class="page-container">
            <!-- HEADER DESKTOP-->
            <header class="header-desktop  d-none d-sm-block">
                <div class="section__content section__content--p30">
                    <div class="container-fluid">
                        <div class="header-wrap">
                            <form class="form-header" action="" method="POST">

                            </form>
                            <div class="header-button">

                                <div class="account-wrap">
                                    <div class="account-item clearfix js-item-menu">
                                        
                                        <div class="account-dropdown js-dropdown">
                                            
                                            
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </header>
            <!-- HEADER DESKTOP-->

            <!-- MAIN CONTENT-->
            <div class="main-content">
            <?php echo $this->content; ?>
            </div>
            <!-- END MAIN CONTENT-->
            <!-- END PAGE CONTAINER-->
        </div>

    </div>

    <!-- Jquery JS-->
    <script src="<?php echo $this->basepath('assets/dashboard2/vendor/jquery-3.2.1.min.js') ?>"></script>
    <!-- Bootstrap JS-->
    <script src="<?php echo $this->basepath('assets/dashboard2/vendor/bootstrap-4.1/popper.min.js') ?>"></script>
    <script src="<?php echo $this->basepath('assets/dashboard2/vendor/bootstrap-4.1/bootstrap.min.js') ?>"></script>
    <!-- Vendor JS       -->
    <script src="<?php echo $this->basepath('js/vendor/bootgrid/jquery.bootgrid.min.js') ?>">
    <script src="<?php echo $this->basepath('assets/dashboard2/vendor/slick/slick.min.js') ?>">
    </script>
    <script src="<?php echo $this->basepath('assets/dashboard2/vendor/wow/wow.min.js') ?>"></script>
    <script src="<?php echo $this->basepath('assets/dashboard2/vendor/animsition/animsition.min.js') ?>"></script>
    <script src="<?php echo $this->basepath('assets/dashboard2/vendor/bootstrap-progressbar/bootstrap-progressbar.min.js') ?>">
    </script>
    <script src="<?php echo $this->basepath('assets/dashboard2/vendor/counter-up/jquery.waypoints.min.js') ?>"></script>
    <script src="<?php echo $this->basepath('assets/dashboard2/vendor/counter-up/jquery.counterup.min.js') ?>">
    </script>
    <script src="<?php echo $this->basepath('assets/dashboard2/vendor/circle-progress/circle-progress.min.js') ?>"></script>
    <script src="<?php echo $this->basepath('assets/dashboard2/vendor/perfect-scrollbar/perfect-scrollbar.js') ?>"></script>
    <script src="<?php echo $this->basepath('assets/dashboard2/vendor/chartjs/Chart.bundle.min.js') ?>"></script>
    <script src="<?php echo $this->basepath('assets/dashboard2/vendor/select2/select2.min.js') ?>">
    </script>

    <!-- Main JS-->
    <script src="<?php echo $this->basepath('assets/dashboard2/js/main.js') ?>"></script>
    <?php echo $this->headScript(); ?>
</body>

</html>
<!-- end document-->
