<!DOCTYPE html>
<html lang="es">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>Linkeventt - Plataforma digital para eventos</title>

  <!-- Bootstrap core CSS -->
  <link href="<?php echo $this->basepath('assets/landing/vendor/bootstrap/css/bootstrap.min.css') ?>" rel="stylesheet">

  <!-- Custom fonts for this template -->
  <link href="https://fonts.googleapis.com/css?family=Catamaran:100,200,300,400,500,600,700,800,900" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Lato:100,100i,300,300i,400,400i,700,700i,900,900i" rel="stylesheet">

  <!-- Custom styles for this template -->
  <link href="<?php echo $this->basepath('assets/landing/css/one-page-wonder.min.css') ?>" rel="stylesheet">
  <link href="<?php echo $this->basepath('assets/landing/css/custom.css') ?>" rel="stylesheet">
  <style>
      .navbar-custom{
          background-color: #fff;
      }
      
      header.masthead{
          background: 
            /* top, transparent red */ 
            linear-gradient(
              rgba(128, 0, 0, 0.45), 
              rgba(128, 0, 0, 0.45)
            ),
            /* bottom, image */
            url(/assets/landing/img/landing1.jpg);
          background-size: cover;
      }
  </style>
  <?php echo $this->headLink(); ?>
</head>

<body>

  <!-- Navigation -->
  <nav class="navbar navbar-expand-lg navbar-light navbar-custom fixed-top">
    <div class="container">
      <a class="navbar-brand" href="#">
          <img src="<?php echo $this->basepath('assets/landing/img/logo.png') ?>" class="img-fluid" style="height: 50px">
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <a class="nav-link" href="#">Eventos</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Registro</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Entrar</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>

  <!-- content -->
  <div style='margin-top: 90px'>
    <?php echo $this->content; ?>
  </div>

<!--  <section>
    <div class="container">
      <div class="row align-items-center">
        <div class="col-lg-6 order-lg-2">
          <div class="p-5">
            <img class="img-fluid rounded-circle" src="<?php echo $this->basepath('assets/landing/img/03.jpg') ?>" alt="">
          </div>
        </div>
        <div class="col-lg-6 order-lg-1">
          <div class="p-5">
            <h2 class="display-4">Let there be rock!</h2>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quod aliquid, mollitia odio veniam sit iste esse assumenda amet aperiam exercitationem, ea animi blanditiis recusandae! Ratione voluptatum molestiae adipisci, beatae obcaecati.</p>
          </div>
        </div>
      </div>
    </div>
  </section>-->

  <!-- Footer -->
  <footer class="py-5 bg-black">
    <div class="container">
      <p class="m-0 text-center text-white">&copy; Linkeventt 2019</p>
    </div>
    <!-- /.container -->
  </footer>

  <!-- Bootstrap core JavaScript -->
  <script src="<?php echo $this->basepath('vendor/jquery/jquery.min.js') ?>"></script>
  <script src="<?php echo $this->basepath('vendor/bootstrap/js/bootstrap.bundle.min.js') ?>"></script>
  <?php echo $this->headScript(); ?>
</body>

</html>
