<div id="sliders-container">
					</div>
						
							
		
		
						<div id="main" role="main" class="clearfix width-100" style="padding-left:30px;padding-right:30px">
			<div class="fusion-row" style="max-width:100%;">
<div id="content" class="full-width">
			<div id="post-8" class="post-8 page type-page status-publish hentry">
			
			<span class="entry-title rich-snippet-hidden">
			Ficha Técnica		</span>
	
			<span class="vcard rich-snippet-hidden">
			<span class="fn">
				<a href="../author/admin/index.html" title="Entradas de admin" rel="author">admin</a>			</span>
		</span>
	
			<span class="updated rich-snippet-hidden">
			2017-06-17T11:12:43+00:00		</span>
	
						<div class="post-content">
				<div id="dslc-theme-content"><div id="dslc-theme-content-inner"><div  class="fusion-fullwidth fullwidth-box fusion-blend-mode nonhundred-percent-fullwidth"  style='background-color: rgba(255,255,255,0);background-position: center center;background-repeat: no-repeat;padding-top:0px;padding-right:30px;padding-bottom:0px;padding-left:30px;'><div class="fusion-builder-row fusion-row "><div  class="fusion-layout-column fusion_builder_column fusion_builder_column_1_1  fusion-one-full fusion-column-first fusion-column-last 1_1"  style='margin-top:0px;margin-bottom:40px;'>
					<div class="fusion-column-wrapper" style="background-position:left top;background-repeat:no-repeat;-webkit-background-size:cover;-moz-background-size:cover;-o-background-size:cover;background-size:cover;"  data-bg-url="">
						<img src="../wp-content/uploads/2017/06/FICHATECNICA_001.png" style="width:100%;"> <div class="fusion-clearfix"></div>

					</div>
				</div></div></div><div  class="fusion-fullwidth fullwidth-box fusion-blend-mode nonhundred-percent-fullwidth"  style='background-color: rgba(255,255,255,0);background-position: center center;background-repeat: no-repeat;padding-top:10px;padding-right:30px;padding-bottom:0px;padding-left:30px;'><div class="fusion-builder-row fusion-row "><div  class="fusion-layout-column fusion_builder_column fusion_builder_column_1_1  fusion-one-full fusion-column-first fusion-column-last 1_1"  style='margin-top:0px;margin-bottom:40px;'>
					<div class="fusion-column-wrapper" style="background-position:left top;background-repeat:no-repeat;-webkit-background-size:cover;-moz-background-size:cover;-o-background-size:cover;background-size:cover;"  data-bg-url="">
						<img src="../wp-content/uploads/2017/06/FICHATECNICA_002.png" style="width:100%;"><div class="fusion-clearfix"></div>

					</div>
				</div></div></div>
</div></div>							</div>
												</div>
	</div>
					
				</div>  <!-- fusion-row -->
			</div>  <!-- #main -->