  <header class="masthead text-center text-white">
    <div class="masthead-content">
      <div class="container">
        <h1 class="masthead-heading mb-0">Gestione su evento</h1>
        <h2 class="masthead-subheading mb-0">sin complicaciones</h2>
        <a href="<?php echo $this->basepath('/eventos/create') ?>" class="btn btn-primary btn-xl rounded-pill mt-5">Crear evento</a>
      </div>
    </div>
<!--    <div class="bg-circle-1 bg-circle"></div>
    <div class="bg-circle-2 bg-circle"></div>
    <div class="bg-circle-3 bg-circle"></div>
    <div class="bg-circle-4 bg-circle"></div>-->
  </header>

  <section>
    <div class="container">
      <div class="row align-items-center">
        <div class="col-lg-6 order-lg-2">
          <div class="p-5">
            <img class="img-fluid rounded-circle" src="<?php echo $this->basepath('assets/landing/img/01.jpg') ?>" alt="">
          </div>
        </div>
        <div class="col-lg-6 order-lg-1">
          <div class="p-5">
            <h2 class="display-4">Solución para su evento</h2>
            <p>Una plataforma que se adapta a la gestión de conferencias, 
                talleres, foros, congresos, ferias y mucho más. Organice 
                las tareas del evento con su equipo y administre su 
                infomación de manera fluida. </p>
          </div>
        </div>
      </div>
    </div>
  </section>

  <section>
    <div class="container">
      <div class="row align-items-center">
        <div class="col-lg-6">
          <div class="p-5">
            <img class="img-fluid rounded-circle" src="<?php echo $this->basepath('assets/landing/img/02.jpg') ?>" alt="">
          </div>
        </div>
        <div class="col-lg-6">
          <div class="p-5">
            <h2 class="display-4">Datos en tiempo real</h2>
            <p>Registre y monitoree las estadísticas de su evento: 
                entradas, ingresos, asistentes, entre otros.
            Automatice las notificaciones para los asistentes del evento, 
            realice campañas de marketing digital para conseguir más entradas.
            </p>
          </div>
        </div>
      </div>
    </div>
  </section>